### ISSUE TITLE
ci: duplicate workflow run for first commit of new branches

### ISSUE THREAD

**Issue by DerYeger** [maevsi/maevsi#403]
The `ci` workflow runs twice for the initial commit of a newly created branch.
Once for the `push` and again for the `create` event.

Instead of
```yml
name: CI

on: [create, pull_request, push]
```

something along the lines of
```yml
on:
  pull_request:
  push:
  release:
    types: [created]
```

could be used.
This would still run CI for newly created tags/releases, but not for the creation of a branch.
